name: Auto merge
on: 
  #pull_request
  repository_dispatch:
  workflow_dispatch:
  #schedule:
  #    - cron: 0 20 */4 * *
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: auto-pull
        id: merge
        uses: KeisukeYamashita/auto-pull-request-merge@main
        with:
          intervalSeconds: 1
          timeoutSeconds: 60
          labels: need,need2
          labelsStrategy: atLeastOne
          ignoreLabels: ignore
          
      - name: Create Comment
        uses: KeisukeYamashita/create-comment@main
        with:
          comment: ${{ steps.merge.outputs.merged }}
